#!/bin/bash

echo "Create $DATABASE_NAME and $MYSQL_USER..."
mysql -h $MYSQL_HOST -u root -p$MYSQL_ROOT_PASSWORD \
  -e " CREATE DATABASE IF NOT EXISTS $DATABASE_NAME;
        CREATE USER '$MYSQL_USER'@'%' IDENTIFIED BY '$MYSQL_PASSWORD';
        GRANT ALL PRIVILEGES ON $DATABASE_NAME.* TO '$MYSQL_USER'@'%';
        FLUSH PRIVILEGES;"