# Edit all ...!
version: "3.7"
services:
  mariadb:
    image: mariadb:10.6.4
    container_name: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=...
    volumes:
      - mariadb_data:/var/lib/mysql
  mymediawiki:
    image: dataspects/mediawiki:1.36.2-3.2.3_211101-x86_64
    container_name: mymediawiki
    restart: always
    depends_on:
      - mariadb
    volumes:
      - mymediawiki_config:/var/www/config
      - mymediawiki_extensions:/var/www/html/w/extensions
      - mymediawiki_skins:/var/www/html/w/skins
      - mymediawiki_vendor:/var/www/html/w/vendor
      - mymediawiki_images:/var/www/html/w/images
      - /home/.../mymediawiki/composer.local.json:/var/www/html/w/composer.local.json
      - /home/.../mymediawiki/composer.local.lock:/var/www/html/w/composer.local.lock
    environment:
      - AWS_S3_API=...
      - AWS_ACCESS_KEY_ID=...
      - AWS_SECRET_ACCESS_KEY=...
      - AWS_S3_BUCKET=...
      - RESTIC_PASSWORD=...
      - MYSQL_PASSWORD=...
      - DATABASE_NAME=...
      - MYSQL_USER=...
      - MYSQL_HOST=mariadb
      - mymediawiki_ADMIN_USERNAME=...
      - mymediawiki_ADMIN_PASSWORD=...
    ports:
      - 8080:80
    extra_hosts:
      - "...:127.0.0.1"
volumes:
  mariadb_data:
    driver: local
    name: mariadb_data
  mymediawiki_config:
    driver: local
    name: mymediawiki_config
  mymediawiki_extensions:
    driver: local
    name: mymediawiki_extensions
  mymediawiki_skins:
    driver: local
    name: mymediawiki_skins
  mymediawiki_vendor:
    driver: local
    name: mymediawiki_vendor
  mymediawiki_images:
    driver: local
    name: mymediawiki_images